# Generated by Django 4.2.7 on 2023-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
